# AWS
aws_access_key: # Use environment variables - http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
aws_secret_key: # Use environment variables - http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
key_name: lab-ec2
aws_region: us-east-1
vpc_id: vpc-6a29fe0c
vpc_subnet_id: subnet-5092057d
ami_id: ami-71b7750b #AMI Debian Stretch 9
instance_type: t2.large
security_group_name: jenkins_stack_rules
# AWS EC2
ansible_ssh_private_key_file: /Users/alexbaptista/.ssh/lab-ec2.pem
ansible_user: admin
ansible_become: yes
ansible_become_method: sudo
# Jenkins Config
jenkins_home: /home/jenkins
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_plugins: cloudbees-folder antisamy-markup-formatter build-timeout credentials-binding timestamper ws-cleanup ant gradle workflow-aggregator github-branch-source pipeline-github-lib pipeline-stage-view git subversion ssh-slaves matrix-auth pam-auth ldap email-ext mailer
