jenkins_home: /home/jenkins
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_plugins: cloudbees-folder antisamy-markup-formatter build-timeout credentials-binding timestamper ws-cleanup ant gradle workflow-aggregator github-branch-source pipeline-github-lib pipeline-stage-view git subversion ssh-slaves matrix-auth pam-auth ldap email-ext mailer
