- name: create jenkins folder
  file:
    path: /home/jenkins
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: install pip
  apt: name=python-pip state=present

- name: install module docker-py
  pip: name=docker-py state=present

- name: create jenkins container
  docker_container:
    name: jenkins
    image: docker.io/jenkins/jenkins:lts
    pull: yes
    state: started
    volumes:
      - "/home/jenkins:/var/jenkins_home:rw"
    published_ports:
      - "8080:8080"
      - "50000:50000"
